[build]
  publish = "."

[[redirects]]
  from = "/trade-journal"
  to = "/trade-journal/dist/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/trade-journal/"
  to = "/trade-journal/dist/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
